module CheckoutIntents
  module Resources
    class CheckoutIntents
      class Shipments
        def list: (
          String id,
          ?after: String,
          ?before: String,
          ?limit: Float,
          ?request_options: ::CheckoutIntents::request_opts
        ) -> ::CheckoutIntents::Internal::CursorPagination[::CheckoutIntents::Models::shipment]

        def initialize: (client: ::CheckoutIntents::Client) -> void
      end
    end
  end
end
