module CheckoutIntents
  class BaseCheckoutIntent = CheckoutIntents::Models::BaseCheckoutIntent

  module Betas = CheckoutIntents::Models::Betas

  class BillingGetBalanceParams = CheckoutIntents::Models::BillingGetBalanceParams

  class BillingListTransactionsParams = CheckoutIntents::Models::BillingListTransactionsParams

  class BrandRetrieveParams = CheckoutIntents::Models::BrandRetrieveParams

  class Buyer = CheckoutIntents::Models::Buyer

  module CheckoutIntent = CheckoutIntents::Models::CheckoutIntent

  class CheckoutIntentAddPaymentParams = CheckoutIntents::Models::CheckoutIntentAddPaymentParams

  class CheckoutIntentConfirmParams = CheckoutIntents::Models::CheckoutIntentConfirmParams

  class CheckoutIntentCreateParams = CheckoutIntents::Models::CheckoutIntentCreateParams

  class CheckoutIntentListParams = CheckoutIntents::Models::CheckoutIntentListParams

  class CheckoutIntentPurchaseParams = CheckoutIntents::Models::CheckoutIntentPurchaseParams

  class CheckoutIntentRetrieveParams = CheckoutIntents::Models::CheckoutIntentRetrieveParams

  class CheckoutSession = CheckoutIntents::Models::CheckoutSession

  class Money = CheckoutIntents::Models::Money

  class Offer = CheckoutIntents::Models::Offer

  module PaymentMethod = CheckoutIntents::Models::PaymentMethod

  class Product = CheckoutIntents::Models::Product

  module ProductAvailability = CheckoutIntents::Models::ProductAvailability

  class ProductImage = CheckoutIntents::Models::ProductImage

  class ProductLookupParams = CheckoutIntents::Models::ProductLookupParams

  class VariantSelection = CheckoutIntents::Models::VariantSelection
end
