module CheckoutIntents
  module Models
    module CheckoutIntents
      type shipment_list_params =
        { after: String, before: String, limit: Float }
        & ::CheckoutIntents::Internal::Type::request_parameters

      class ShipmentListParams < ::CheckoutIntents::Internal::Type::BaseModel
        extend ::CheckoutIntents::Internal::Type::RequestParameters::Converter
        include ::CheckoutIntents::Internal::Type::RequestParameters

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader before: String?

        def before=: (String) -> String

        attr_reader limit: Float?

        def limit=: (Float) -> Float

        def initialize: (
          ?after: String,
          ?before: String,
          ?limit: Float,
          ?request_options: CheckoutIntents::request_opts
        ) -> void

        def to_hash: -> {
          after: String,
          before: String,
          limit: Float,
          request_options: ::CheckoutIntents::RequestOptions
        }
      end
    end
  end
end
