module CheckoutIntents
  module Models
    type billing_get_balance_response = { balance: ::CheckoutIntents::Money }

    class BillingGetBalanceResponse < ::CheckoutIntents::Internal::Type::BaseModel
      attr_accessor balance: ::CheckoutIntents::Money

      def initialize: (balance: ::CheckoutIntents::Money) -> void

      def to_hash: -> { balance: ::CheckoutIntents::Money }
    end
  end
end
