module CheckoutIntents
  module Models
    type payment_gateway_create_session_params =
      { gateway: ::CheckoutIntents::Models::payment_gateway }
      & ::CheckoutIntents::Internal::Type::request_parameters

    class PaymentGatewayCreateSessionParams < ::CheckoutIntents::Internal::Type::BaseModel
      extend ::CheckoutIntents::Internal::Type::RequestParameters::Converter
      include ::CheckoutIntents::Internal::Type::RequestParameters

      attr_accessor gateway: ::CheckoutIntents::Models::payment_gateway

      def initialize: (
        gateway: ::CheckoutIntents::Models::payment_gateway,
        ?request_options: ::CheckoutIntents::request_opts
      ) -> void

      def to_hash: -> {
        gateway: ::CheckoutIntents::Models::payment_gateway,
        request_options: ::CheckoutIntents::RequestOptions
      }
    end
  end
end
