module CheckoutIntents
  module Models
    type product_lookup_params =
      { url: String } & ::CheckoutIntents::Internal::Type::request_parameters

    class ProductLookupParams < ::CheckoutIntents::Internal::Type::BaseModel
      extend ::CheckoutIntents::Internal::Type::RequestParameters::Converter
      include ::CheckoutIntents::Internal::Type::RequestParameters

      attr_accessor url: String

      def initialize: (
        url: String,
        ?request_options: ::CheckoutIntents::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        request_options: ::CheckoutIntents::RequestOptions
      }
    end
  end
end
