module CheckoutIntents
  module Models
    type product =
      {
        id: String,
        availability: CheckoutIntents::Models::product_availability,
        brand: String?,
        description: String?,
        images: ::Array[CheckoutIntents::ProductImage],
        is_purchasable: bool,
        name: String,
        price: CheckoutIntents::Money,
        sku: String?,
        url: String
      }

    class Product < CheckoutIntents::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor availability: CheckoutIntents::Models::product_availability

      attr_accessor brand: String?

      attr_accessor description: String?

      attr_accessor images: ::Array[CheckoutIntents::ProductImage]

      attr_accessor is_purchasable: bool

      attr_accessor name: String

      attr_accessor price: CheckoutIntents::Money

      attr_accessor sku: String?

      attr_accessor url: String

      def initialize: (
        id: String,
        availability: CheckoutIntents::Models::product_availability,
        brand: String?,
        description: String?,
        images: ::Array[CheckoutIntents::ProductImage],
        is_purchasable: bool,
        name: String,
        price: CheckoutIntents::Money,
        sku: String?,
        url: String
      ) -> void

      def to_hash: -> {
        id: String,
        availability: CheckoutIntents::Models::product_availability,
        brand: String?,
        description: String?,
        images: ::Array[CheckoutIntents::ProductImage],
        is_purchasable: bool,
        name: String,
        price: CheckoutIntents::Money,
        sku: String?,
        url: String
      }
    end
  end
end
