module CheckoutIntents
  module Models
    type shipment_retrieve_params =
      {  } & ::CheckoutIntents::Internal::Type::request_parameters

    class ShipmentRetrieveParams < ::CheckoutIntents::Internal::Type::BaseModel
      extend ::CheckoutIntents::Internal::Type::RequestParameters::Converter
      include ::CheckoutIntents::Internal::Type::RequestParameters

      def initialize: (
        ?request_options: ::CheckoutIntents::request_opts
      ) -> void

      def to_hash: -> { request_options: ::CheckoutIntents::RequestOptions }
    end
  end
end
