module CheckoutIntents
  module Models
    type shipment_list_params =
      {
        after: String,
        before: String,
        ids: ::Array[String],
        limit: Float,
        status: ::Array[::CheckoutIntents::Models::ShipmentListParams::status]
      }
      & ::CheckoutIntents::Internal::Type::request_parameters

    class ShipmentListParams < ::CheckoutIntents::Internal::Type::BaseModel
      extend ::CheckoutIntents::Internal::Type::RequestParameters::Converter
      include ::CheckoutIntents::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader ids: ::Array[String]?

      def ids=: (::Array[String]) -> ::Array[String]

      attr_reader limit: Float?

      def limit=: (Float) -> Float

      attr_reader status: ::Array[::CheckoutIntents::Models::ShipmentListParams::status]?

      def status=: (
        ::Array[::CheckoutIntents::Models::ShipmentListParams::status]
      ) -> ::Array[::CheckoutIntents::Models::ShipmentListParams::status]

      def initialize: (
        ?after: String,
        ?before: String,
        ?ids: ::Array[String],
        ?limit: Float,
        ?status: ::Array[::CheckoutIntents::Models::ShipmentListParams::status],
        ?request_options: ::CheckoutIntents::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        ids: ::Array[String],
        limit: Float,
        status: ::Array[::CheckoutIntents::Models::ShipmentListParams::status],
        request_options: ::CheckoutIntents::RequestOptions
      }

      type status =
        :out_for_delivery
        | :delivered
        | :shipped
        | :canceled
        | :delayed
        | :ordered

      module Status
        extend ::CheckoutIntents::Internal::Type::Enum

        OUT_FOR_DELIVERY: :out_for_delivery
        DELIVERED: :delivered
        SHIPPED: :shipped
        CANCELED: :canceled
        DELAYED: :delayed
        ORDERED: :ordered

        def self?.values: -> ::Array[::CheckoutIntents::Models::ShipmentListParams::status]
      end
    end
  end
end
