module CheckoutIntents
  module Models
    type shipment_retrieve_params =
      { id: String } & ::CheckoutIntents::Internal::Type::request_parameters

    class ShipmentRetrieveParams < ::CheckoutIntents::Internal::Type::BaseModel
      extend ::CheckoutIntents::Internal::Type::RequestParameters::Converter
      include ::CheckoutIntents::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: ::CheckoutIntents::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        request_options: ::CheckoutIntents::RequestOptions
      }
    end
  end
end
