#!/usr/bin/env bash

set -e

cd -- "$(dirname -- "$0")/.."

echo "==> Running formatters"
bundle exec rake format "$@"

echo "==> Fixing absolute references"
ruby scripts/fix-absolute-references

echo "==> Auto-correcting style issues"
bundle exec rubocop -A --fail-level fatal lib/
